-- Состояние ребенка при рождении (образец)
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 10, null, 'Состояние ребенка при рождении', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Закричал
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 20, null, 'Закричал', '', '', null, 'String', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Крик
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 30, null, 'Крик', '', '', null, 'String', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Двигательная активность
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 40, null, 'Двигательная активность', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Кожные покровы и видимые слизистые
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 50, null, 'Кожные покровы и видимые слизистые', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Пуповинный остаток (с вариантами значений)
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 60, null, 'Пуповинный остаток', '', '', null, 'String', "'обработан','наложен зажим','скоба Роговина','шелковая лигатура','асептическая повязка'", '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Голова
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 70, null, 'Голова', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Кости черепа
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 80, null, 'Кости черепа', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Родовая опухоль
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 90, null, 'Родовая опухоль', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Б.Р.
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 100, null, 'Б.Р.', '', '', null, 'String', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- М.Р.
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 110, null, 'М.Р.', '', '', null, 'String', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Швы
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 120, null, 'Швы', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Глазная симптоматика
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 130, null, 'Глазная симптоматика', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Мышечный тонус
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 140, null, 'Мышечный тонус', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Рефлексы н/р
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 150, null, 'Рефлексы н/р', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Тоны сердца
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 160, null, 'Тоны сердца', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- ЧСС (изменено на String)
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 170, null, 'ЧСС', '', '', null, 'String', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- ЧД (изменено на String)
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 180, null, 'ЧД', '', '', null, 'String', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Дыхание через нос
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 190, null, 'Дыхание через нос', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Грудная клетка
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 200, null, 'Грудная клетка', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Ключицы (пальпаторно) (с вариантами значений)
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 210, null, 'Ключицы (пальпаторно)', '', '', null, 'String', "'крепитации нет'", '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Перкуторно над легкими
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 220, null, 'Перкуторно над легкими', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Аускультативно дыхание
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 230, null, 'Аускультативно дыхание', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Живот (с вариантами значений)
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 240, null, 'Живот', '', '', null, 'Text', "'доступен глубокой пальпации'", '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Печень
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 250, null, 'Печень', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Селезенка
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 260, null, 'Селезенка', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);

-- Половые органы (с вариантами значений)
INSERT INTO s11.actionpropertytype (deleted, actionType_id, idx, template_id, name, shortName, descr, unit_id, typeName, valueDomain, defaultValue, isVector, norm, sex, age, penalty, penaltyUserProfile, penaltyDiagnosis, visibleInJobTicket, visibleInTableRedactor, isAssignable, test_id, defaultEvaluation, canChangeOnlyOwner, isActionNameSpecifier, laboratoryCalculator, inActionsSelectionTable, redactorSizeFactor, isFrozen, typeEditable, visibleInDR, userProfile_id, userProfileBehaviour, copyModifier, isVitalParam, vitalParamId, isODIIParam, customSelect, autoFieldUserProfile, formulaAlias, ticketsNeeded, incrementOnSave, orientation, parent_id, autoFillAutoField, color, epic)
VALUES (0, 65378, 270, null, 'Половые органы', '', '', null, 'Text', '', '', 0, '', 0, '', 0, null, null, 0, 0, 0, null, 0, 0, 0, null, 0, 0, 0, 1, 0, null, 0, 1, 0, null, 0, null, null, null, null, 0, 'v', null, 0, null, null);